services:
    db:
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: example-test #needs overriding
            POSTGRES_USER: test-user
            POSTGRES_PASSWORD: password